# Generated by Django 4.0.4 on 2022-05-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplelo', '0002_player_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr1', models.CharField(max_length=20)),
                ('kd1', models.CharField(max_length=20)),
                ('kak1', models.CharField(max_length=20)),
                ('kr2', models.CharField(max_length=20)),
                ('kd2', models.CharField(max_length=20)),
                ('kak2', models.CharField(max_length=20)),
                ('kr3', models.CharField(max_length=20)),
                ('kd3', models.CharField(max_length=20)),
                ('kak3', models.CharField(max_length=20)),
                ('kr4', models.CharField(max_length=20)),
                ('kd4', models.CharField(max_length=20)),
                ('kak4', models.CharField(max_length=20)),
                ('kr5', models.CharField(max_length=20)),
                ('kd5', models.CharField(max_length=20)),
                ('kak5', models.CharField(max_length=20)),
                ('kr6', models.CharField(max_length=20)),
                ('kd6', models.CharField(max_length=20)),
                ('kak6', models.CharField(max_length=20)),
                ('kr7', models.CharField(max_length=20)),
                ('kd7', models.CharField(max_length=20)),
                ('kak7', models.CharField(max_length=20)),
                ('kr8', models.CharField(max_length=20)),
                ('kd8', models.CharField(max_length=20)),
                ('kak8', models.CharField(max_length=20)),
                ('kr9', models.CharField(max_length=20)),
                ('kd9', models.CharField(max_length=20)),
                ('kak9', models.CharField(max_length=20)),
                ('kr10', models.CharField(max_length=20)),
                ('kd10', models.CharField(max_length=20)),
                ('kak10', models.CharField(max_length=20)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='pplelo.player')),
                ('player10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player10', to='pplelo.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='pplelo.player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='pplelo.player')),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='pplelo.player')),
                ('player5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='pplelo.player')),
                ('player6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='pplelo.player')),
                ('player7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='pplelo.player')),
                ('player8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='pplelo.player')),
                ('player9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player9', to='pplelo.player')),
            ],
        ),
    ]
