# Generated by Django 4.0.4 on 2022-05-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplelo', '0004_rename_matches_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
