# Generated by Django 4.0.4 on 2022-05-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pplelo', '0005_match_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='kak1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak10',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak4',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak5',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak6',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak7',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak8',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kak9',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd10',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd4',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd5',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd6',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd7',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd8',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kd9',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr10',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr4',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr5',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr6',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr7',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr8',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kr9',
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr', models.CharField(max_length=20)),
                ('kd', models.CharField(max_length=20)),
                ('kak', models.CharField(max_length=20)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pplelo.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistic', to='pplelo.player')),
            ],
        ),
    ]
