# Generated by Django 4.0.4 on 2022-05-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplelo', '0007_alter_match_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='win',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
