# Generated by Django 4.0.4 on 2022-05-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplelo', '0009_alter_statistic_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='name_opponents_team',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
