# Generated by Django 4.0.4 on 2022-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplelo', '0011_statistic_game_map_statistic_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='match_id_string',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
