# Generated by Django 4.0.4 on 2022-05-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplelo', '0012_statistic_match_id_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='nickname_player',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
